---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - chaos.com.softsage.storagechaos
  resources:
  - filesystemchaosexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.com.softsage.storagechaos
  resources:
  - filesystemchaosexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - chaos.com.softsage.storagechaos
  resources:
  - filesystemchaosexperiments/status
  verbs:
  - get
  - patch
  - update
